### PR TITLE
add variables support

### PR DESCRIPTION
**Pull request by wensonsmith**
pass the travis test

### CODE REVIEW

**Comment by vmitchell85** [comment]
Any plans to get this merged @joetannenbaum ???

**Comment by joetannenbaum** [comment]
All set!

**Comment by vmitchell85** [comment]
@joetannenbaum Would you mind tagging another release so I can use packagist/composer?

**Comment by joetannenbaum** [comment]
For sure! Just tagged 0.1.1. 👍

**Pull request merged**
