### PR TITLE
Make the filtering case insensitive

### PR DESCRIPTION
**Pull request by godbout**
This makes the filtering of results case insensitive. It's the default of how Alfred itself works, and I find it gives a much better using experience.

### CODE REVIEW

**Comment by godbout** [comment]
I'm coming back here because I keep using your workflow instead of my fork 😂️
Any update on incorporating (or rejecting) this PR?

**Comment by godbout** [comment]
Even better. Now the comparison doesn't care about accents. A "ukkei" will return results like "ūkkéi" (house in Cantonese :p).

**Comment by godbout** [comment]
Actually the last PR is wrong. Sorry about that. Thought I solved the pb with accents but nope.

**Comment by godbout** [comment]
This PR is back to using stristr. Same as your workflow expect that the comparisons are case-insensitive.

**Comment by joetannenbaum** [comment]
Looks good, thanks @godbout!

**Comment by godbout** [comment]
Welcome. Thanks for the merge! Gonna close #3 then.

**Pull request merged**
