### PR TITLE
add icon compatibility to mods

### PR DESCRIPTION
**Pull request by edwinallan**
see alfred docs

### CODE REVIEW

**Comment by edwinallan** [comment]
sorry, not sure how to git 
I'll let you check the small changes I made and merge if you want.

**Comment by joetannenbaum** [comment]
Where in the docs can you add icons to the modifiers? Can you provide a link?

**Comment by rutinerad** [comment]
@joetannenbaum https://www.alfredapp.com/help/workflows/inputs/script-filter/json/

> From Alfred 3.4.1, you can define an `icon` and `variables` for each object in the mods object.

The reason why I found this issue was that I wanted to add `variables` to my mods. For instance when passing a url, the mod might send an arg 'search' instead of 'open' and needs to also pass the url and the best place to do that seems to be in the variables.

**Comment by rutinerad** [comment]
Also I could do a pull request to add variables if you let me know what the method signature should be. Should that parameter just be added at the end as well, like @edwinallan did?

**Comment by jk** [comment]
@rutinerad Looks like you've forgotten adapting the unit tests to honor the JSON keys.

**Comment by joetannenbaum** [comment]
I know this PR is very old but this is now in the 1.0.0 release! You can find documentation for it here: https://www.alfredphpworkflows.com/docs/items/modifier-keys

**Pull request closed without merging**
